# -*- coding: utf-8 -*-
"""Explorartory analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LptxieO8MlNdUp9Np0qF9PnHdxSv85zg
"""

import pandas as pd

df=pd.read_excel('/content/Timeseries.xlsx')

df.isnull().sum()

df.head(2)

"""uni variate analysis"""

df.columns

import plotly.express as px

px.histogram(df,x='Sales',nbins=20)
#majority of the sales is btwn 0 t0 1000
nbin is used for breaking the histogram in equal range

px.histogram(df,x='Quantity')
# more quantity  shipped is 2 and 3

"""uni variate analysis"""

df.columns

df['Ship Mode'].value_counts().plot(kind='bar')
# standard class has more count

df['Region'].value_counts().plot(kind='bar')
# west has more count

df['Category'].value_counts().plot(kind='bar')
#office supplies has more count

"""bi variate analysis"""

df.columns

px.scatter(df,x='Sales',y='Profit')

import seaborn as sns

sns.scatterplot(df,x='Sales',y='Profit')

sns.regplot(df,x='Sales',y='Profit')

df[['Sales','Profit']].corr()

px.scatter(df,x='Sales',y='Profit')
import seaborn as sns
sns.scatterplot(df,x='Sales',y='Profit')
sns.regplot(df,x='Sales',y='Profit')
df.columns
df[['Sales','Profit']].corr()

"""Outlier"""

px.box(df,y='Sales')
# the values above 498.26-outlier

